/*
	DO NOT EDIT THIS FILE

	It's used only to render the <Fwidgets /> component, which then listens for
	calls from the main thread and renders the corresponding UI controls.
 */
import { render } from "@create-figma-plugin/ui";
import { Fwidgets } from "fwidgets/ui";

export default render(Fwidgets);
