/*
	DO NOT EDIT THIS FILE

	It's used only to set up the UI thread to listen for calls from the main
	thread and then render the UI controls.
 */
import { render } from "@create-figma-plugin/ui";
import { Fwidgets } from "fwidgets/ui";

export default render(Fwidgets);
